export const TRANSFORM_TEXT='TRANSFORM_TEXT';
export const TRANSFORM_DONE= 'TRANSFORM_TEXT_DONE';
export const TRANSFORM_ERROR= 'TRANSFORM_TEXT_ERROR';
export const GET_TRANSFORM_TEXT= 'GET_TRANSFORM_TEXT_HISTORY';
export const SAVE_TRANSFORM_TEXT= 'SAVE_TRANSFORM_TEXT_HISTORY';

export const TRANSFORM_TEXT_HISTORY= 'TRANSFORM_TEXT_HISTORY';

