export const TRANSFORM_TEXT='TRANSFORM_TEXT';
export const TRANSFORM_DONE= 'TRANSFORM_TEXT_DONE';
export const TRANSFORM_ERROR= 'TRANSFORM_TEXT_ERROR';
export const TRANSFORM_TEXT_HISTORY= 'TRANSFORM_TEXT_ERROR';
